import React, { useEffect, useRef, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { marked } from 'marked';
import {
  ArrowLeft, BookOpen, Clock, FileText,
  Download, Sparkles, ExternalLink, Check
} from 'lucide-react';
import '../styles/library.css';

interface BookModule {
  title: string;
  content: string;
  wordCount: number;
}

interface BookFile {
  slug: string;
  title: string;
  goal: string;
  category: string;
  tags: string[];
  complexity: 'beginner' | 'intermediate' | 'advanced';
  wordCount: number;
  moduleCount: number;
  readingTimeMins: number;
  metaDescription: string;
  generatedAt: string;
  modules: BookModule[];
}

const PUSTAKAM_URL = 'https://pustakam.tanmaysk.in';

// ── Minimal Markdown renderer using `marked` (already in deps) ──
function renderMd(md: string): string {
  // marked is synchronous when no async extensions are used
  return marked.parse(md, { breaks: true, gfm: true }) as string;
}

// ── PDF export using browser print API (no extra libs needed) ───
function exportToPdf(book: BookFile) {
  const printWindow = window.open('', '_blank');
  if (!printWindow) return;

  const chaptersHtml = book.modules
    .map((mod, i) => `
      <div class="chapter">
        <p class="ch-num">Chapter ${i + 1}</p>
        <h2>${mod.title}</h2>
        <div class="ch-body">${renderMd(mod.content)}</div>
      </div>
    `)
    .join('<hr>');

  printWindow.document.write(`<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${book.title}</title>
  <style>
    body { font-family: Georgia, serif; max-width: 720px; margin: 0 auto; padding: 40px 24px; color: #1a1a1a; line-height: 1.7; }
    h1 { font-size: 28px; margin-bottom: 8px; }
    .meta { color: #666; font-size: 13px; margin-bottom: 48px; }
    .chapter { margin-bottom: 48px; page-break-inside: avoid; }
    .ch-num { font-size: 11px; text-transform: uppercase; letter-spacing: 0.1em; color: #7c6af7; margin-bottom: 4px; }
    h2 { font-size: 20px; margin: 0 0 20px; border-bottom: 1px solid #eee; padding-bottom: 10px; }
    h3 { font-size: 16px; }
    p { margin: 0 0 14px; }
    ul, ol { padding-left: 20px; margin: 0 0 14px; }
    li { margin-bottom: 6px; }
    code { background: #f5f5f5; padding: 2px 5px; border-radius: 3px; font-size: 13px; }
    pre { background: #f5f5f5; padding: 14px; border-radius: 6px; overflow-x: auto; }
    hr { border: none; border-top: 1px solid #eee; margin: 40px 0; }
    blockquote { border-left: 3px solid #7c6af7; padding: 8px 16px; background: #fafafa; }
    .footer { margin-top: 64px; text-align: center; color: #999; font-size: 12px; }
  </style>
</head>
<body>
  <h1>${book.title}</h1>
  <p class="meta">
    ${book.wordCount.toLocaleString()} words · ${book.readingTimeMins} min read · ${book.complexity} · Generated by Pustakam AI
  </p>
  ${chaptersHtml}
  <div class="footer">Generated by Pustakam AI — pustakam.tanmaysk.in</div>
</body>
</html>`);

  printWindow.document.close();
  printWindow.focus();
  setTimeout(() => {
    printWindow.print();
  }, 500);
}

export default function BookReaderPage() {
  const { slug } = useParams<{ slug: string }>();
  const [book, setBook] = useState<BookFile | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [activeChapter, setActiveChapter] = useState(0);
  const [pdfLoading, setPdfLoading] = useState(false);
  const [copied, setCopied] = useState(false);
  const [theme, setTheme] = useState<'light' | 'dark'>('dark');
  const chapterRefs = useRef<(HTMLDivElement | null)[]>([]);

  useEffect(() => {
    document.documentElement.setAttribute("data-app-page", "landing-v5");
    
    const saved = window.localStorage.getItem("theme");
    const preferDark = saved === "dark" || (!saved && window.matchMedia("(prefers-color-scheme: dark)").matches);
    const t = preferDark ? "dark" : "light";
    setTheme(t);
    document.documentElement.setAttribute("data-theme", t);

    if (!slug) return;
    setLoading(true);
    fetch(`/library/books/${slug}.json`)
      .then(r => r.ok ? r.json() : Promise.reject('Book not found'))
      .then((data: BookFile) => {
        setBook(data);
        document.title = `${data.title} — Free Book`;
        // Set meta description
        const meta = document.querySelector('meta[name="description"]');
        if (meta) meta.setAttribute('content', data.metaDescription);
        setLoading(false);
      })
      .catch(() => {
        setError('This book could not be found.');
        setLoading(false);
      });
  }, [slug]);

  useEffect(() => {
    document.documentElement.setAttribute("data-theme", theme);
    window.localStorage.setItem("theme", theme);
  }, [theme]);

  // Track which chapter is in view
  useEffect(() => {
    if (!book) return;
    const observer = new IntersectionObserver(
      entries => {
        entries.forEach(e => {
          if (e.isIntersecting) {
            const idx = chapterRefs.current.indexOf(e.target as HTMLDivElement);
            if (idx !== -1) setActiveChapter(idx);
          }
        });
      },
      { rootMargin: '-20% 0px -60% 0px' }
    );
    chapterRefs.current.forEach(el => { if (el) observer.observe(el); });
    return () => observer.disconnect();
  }, [book]);

  const scrollToChapter = (i: number) => {
    chapterRefs.current[i]?.scrollIntoView({ behavior: 'smooth', block: 'start' });
  };

  const handlePdf = () => {
    if (!book) return;
    setPdfLoading(true);
    setTimeout(() => {
      exportToPdf(book);
      setPdfLoading(false);
    }, 100);
  };

  const handleCopyLink = () => {
    navigator.clipboard.writeText(window.location.href).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  const generateUrl = book
    ? `${PUSTAKAM_URL}/?topic=${encodeURIComponent(book.goal)}&complexity=${book.complexity}`
    : PUSTAKAM_URL;

  if (loading) {
    return (
      <div className="reader-root">
        {/* Background decoration */}
        <div className="lp-bg-wrapper">
          <div className="lp-grain"></div>
          <div className="lp-grid-original"></div>
        </div>
        <div className="lib-loading" style={{ height: '100vh', position: 'relative', zIndex: 10 }}>
          <div className="lib-spinner" />
          Loading book...
        </div>
      </div>
    );
  }

  if (error || !book) {
    return (
      <div className="reader-root">
        {/* Background decoration */}
        <div className="lp-bg-wrapper">
          <div className="lp-grain"></div>
          <div className="lp-grid-original"></div>
        </div>
        <header className="lv5-nav" style={{ position: 'relative', zIndex: 10 }}>
          <div className="lv5-nav__brand">
            <Link to="/library" className="lv5-nav__link" style={{ padding: '0.4rem 0' }}>
              ← LIBRARY
            </Link>
          </div>
        </header>
        <div className="lib-empty" style={{ paddingTop: 120, position: 'relative', zIndex: 10 }}>
          <BookOpen size={40} style={{ marginBottom: 16, opacity: 0.3 }} />
          <h3>{error || 'Book not found'}</h3>
          <p style={{ marginTop: 8 }}>
            <Link to="/library" style={{ color: 'var(--accent)' }}>← Back to library</Link>
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="reader-root">
      {/* Background decoration matching landing page */}
      <div className="lp-bg-wrapper">
        <div className="lp-grain"></div>
        <div className="lp-grid-original"></div>
        <div className="lp-orb lp-orb-a"></div>
        <div className="lp-orb lp-orb-b"></div>
        <div className="lp-orb lp-orb-c"></div>
      </div>

      {/* Nav */}
      <header className="lv5-nav" style={{ position: 'sticky', top: 0, backdropFilter: 'blur(8px)', background: 'rgba(14, 14, 16, 0.4)', zIndex: 100 }}>
        <div className="lv5-nav__brand">
          <Link to="/library" className="lv5-nav__link" style={{ padding: '0.4rem 0', display: 'flex', gap: '0.5rem', alignItems: 'center' }}>
            ← LIBRARY
          </Link>
        </div>
        <nav className="lv5-nav__links">
          <button
            className="btn-secondary"
            onClick={handleCopyLink}
            style={{ padding: '0.4rem 0.75rem', fontSize: '0.6rem', height: 'auto', border: '1px solid var(--border)' }}
          >
            {copied ? 'COPIED!' : 'SHARE'}
          </button>
          <button
            className="btn-secondary"
            onClick={handlePdf}
            disabled={pdfLoading}
            style={{ padding: '0.4rem 0.75rem', fontSize: '0.6rem', height: 'auto', border: '1px solid var(--border)', marginLeft: '0.3rem' }}
          >
            {pdfLoading ? 'PREPARING...' : 'DOWNLOAD PDF'}
          </button>
          <a
            href={generateUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="lv5-nav__cta"
            style={{ marginLeft: '0.3rem' }}
          >
            GENERATE MY VERSION
          </a>
          <button
            className="lv5-nav__theme"
            onClick={() => setTheme((t) => (t === "dark" ? "light" : "dark"))}
            aria-label="Toggle theme"
            style={{ marginLeft: '0.5rem' }}
          >
            {theme === "dark" ? "☀" : "☾"}
          </button>
        </nav>
      </header>

      {/* Layout */}
      <div className="reader-layout">
        {/* TOC Sidebar */}
        <aside className="reader-toc">
          <h3>Contents</h3>
          {book.modules.map((mod, i) => (
            <button
              key={i}
              className={`reader-toc-item ${activeChapter === i ? 'active' : ''}`}
              onClick={() => scrollToChapter(i)}
            >
              {i + 1}. {mod.title}
            </button>
          ))}
        </aside>

        {/* Main */}
        <main className="reader-main">
          {/* Book Header */}
          <div className="reader-header">
            <div className="reader-header-meta">
              <span className={`reader-complexity ${book.complexity}`}>{book.complexity}</span>
              <span className="reader-category">{book.category}</span>
              {book.tags.slice(0, 2).map(t => (
                <span key={t} className="lib-tag">{t}</span>
              ))}
            </div>

            <h1 className="reader-title">{book.title}</h1>
            <p className="reader-goal">{book.goal}</p>

            <div className="reader-stats">
              <span className="reader-stat"><Clock size={13} /> {book.readingTimeMins} min read</span>
              <span className="reader-stat"><FileText size={13} /> {book.moduleCount} chapters</span>
              <span className="reader-stat"><BookOpen size={13} /> {book.wordCount.toLocaleString()} words</span>
            </div>

            <div className="reader-action-row">
              <button className="btn-secondary" onClick={handlePdf} disabled={pdfLoading}>
                <Download size={14} />
                {pdfLoading ? 'Preparing PDF...' : 'Download PDF'}
              </button>
              <a
                href={generateUrl}
                target="_blank"
                rel="noopener noreferrer"
                className="btn-primary"
              >
                <Sparkles size={14} />
                Generate My Own Version
                <ExternalLink size={12} />
              </a>
            </div>
          </div>

          {/* Chapters */}
          {book.modules.map((mod, i) => (
            <div
              key={i}
              className="reader-chapter"
              ref={el => { chapterRefs.current[i] = el; }}
            >
              <p className="reader-chapter-number">Chapter {i + 1}</p>
              <h2 className="reader-chapter-title">{mod.title}</h2>
              <div
                className="reader-chapter-body"
                dangerouslySetInnerHTML={{ __html: renderMd(mod.content) }}
              />
            </div>
          ))}

          {/* CTA at bottom */}
          <div className="reader-cta-box">
            <h3>Want a book made just for you?</h3>
            <p>
              Generate a fully custom book on any topic — your complexity level, your goals,
              your learning style. Free to try on Pustakam.
            </p>
            <div className="reader-cta-row">
              <a
                href={generateUrl}
                target="_blank"
                rel="noopener noreferrer"
                className="btn-primary"
              >
                <Sparkles size={14} />
                Generate on Pustakam
              </a>
              <Link to="/library" className="btn-secondary">
                ← Browse More Books
              </Link>
            </div>
          </div>
        </main>
      </div>
    </div>
  );
}
